[package]
name = "verified-memory-allocator"
version = "0.1.0"
edition = "2021"

[dependencies]
bit_field = "0.10"
vstd = { version = "0.0.0-2025-08-12-1837", default-features = false }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "bitalloc_compare"
harness = false
