[package]
name = "hvisor-ma"
version = "0.1.0"
edition = "2021"

[dependencies]
bit_field = "0.10"
vstd = { path = "/home/lj/hvisor-projects/verus/source/vstd", default-features = false }

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "bitalloc_compare"
harness = false
